# Generated by Django 4.0.6 on 2022-08-01 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_from_seller'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Что в заказе', 'verbose_name_plural': 'Что в заказах'},
        ),
    ]
