# Generated by Django 4.0.6 on 2022-08-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flowers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Наименование цветка')),
                ('color', models.CharField(blank=True, choices=[('BLUE', 'синий'), ('RED', 'красный'), ('BLACK', 'черный')], max_length=10, verbose_name='Оттенок')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Выставлен на продажу')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество на складе')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='стоимость')),
            ],
        ),
    ]
