# Generated by Django 4.0.6 on 2022-08-01 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_buyer_options_alter_role_options_and_more'),
        ('products', '0002_alter_flowers_options_review'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='ReviewForProduct',
        ),
        migrations.AlterModelOptions(
            name='reviewforproduct',
            options={'verbose_name': 'Отзыв о товаре', 'verbose_name_plural': 'Отзывы о товаре'},
        ),
        migrations.CreateModel(
            name='ReviewForSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Имя')),
                ('text', models.CharField(max_length=5000, verbose_name='Текст отзыва')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.seller')),
            ],
            options={
                'verbose_name': 'Отзыв о продавце',
                'verbose_name_plural': 'Отзывы о продавце',
            },
        ),
    ]
